In [13]:
import numpy as np 
import pandas as pd
import json
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('dark')
%matplotlib inline

def parse_genres(genres_str):
    genres = json.loads(genres_str.replace('\'', '"'))
    
    genres_list = []
    for g in genres:
        genres_list.append(g['name'])

    return '|'.join(genres_list)

### 추천 데이터 로딩
ratings = pd.read_csv('/Users/whitexozu/dev/project/recommend/data/the-movies-dataset/ratings_small.csv')
# ratings.head()
# ratings.describe()

### 특정 한명의 최고 점수 영화중 한개를 random 을 통해 추출 

### 영화 데이터 로딩
# meta = pd.read_csv('/Users/whitexozu/dev/project/recommend/data/the-movies-dataset/movies_metadata.csv', dtype={'popularity': str})
# meta.head()

### 데이터 정제
# meta = meta[['id', 'original_title', 'original_language', 'genres']]
# meta = meta.rename(columns={'id':'movieId'})
# meta = meta.rename(columns={'original_title':'title'})
# meta = meta[meta['original_language'] == 'en']
# meta.movieId = pd.to_numeric(meta.movieId, errors='coerce')
# ratings.movieId = pd.to_numeric(ratings.movieId, errors='coerce')
# meta['genres'] = meta['genres'].apply(parse_genres)
# data = pd.merge(ratings, meta, on='movieId', how='inner')

### 거리 계산을 통해 추천 영화 10 개를 뽑는다

### content base 를 통해 유사도 ??? 뭐더라 ???

              userId        movieId         rating     timestamp
count  100004.000000  100004.000000  100004.000000  1.000040e+05
mean      347.011310   12548.664363       3.543608  1.129639e+09
std       195.163838   26369.198969       1.058064  1.916858e+08
min         1.000000       1.000000       0.500000  7.896520e+08
25%       182.000000    1028.000000       3.000000  9.658478e+08
50%       367.000000    2406.500000       4.000000  1.110422e+09
75%       520.000000    5418.000000       4.000000  1.296192e+09
max       671.000000  163949.000000       5.000000  1.476641e+09